language: php
sudo: false

matrix:
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: SCRUTINIZER=1
      env: PHPUNIT_TEST=1
    - php: 7.3
      env: PHPUNIT_TEST=1
    - php: 7.4
      env: PHPUNIT_TEST=1
    - php: nightly
  allow_failures:
    - php: nightly
    - php: 7.1
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

install:
    - if [ $TRAVIS_PHP_VERSION = 'nightly' ]; then composer install --prefer-dist --ignore-platform-reqs; else composer install --prefer-dist; fi

before_install:
    - composer self-update
    - phpenv config-rm xdebug.ini || true
    - composer require biurad/biurad-http ^0.1
    - composer remove phpunit/phpunit --dev
    - if [ "$PHPUNIT_TEST" == 1 ]; then composer require phpunit/phpunit ^8.5; else composer require phpunit/phpunit ^7.5; fi

before_script:
  - composer update $COMPOSER_FLAGS --prefer-dist

script:
  - stty cols 120
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover clover.xml

after_script:
  - if [ "$SCRUTINIZER" == 1 ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format php-clover coverage.xml; fi
